export const WEBSITE_URL = "https://www.igorzanella.dev";
export const LINKEDIN_URL = "https://it.linkedin.com/in/igor-zanella";
export const GITHUB_URL = "https://github.com/IgorZanellaDev";
export const TWITTER_URL = "https://twitter.com/IgorZanellaDev";
export const DEVTO_URL = "https://dev.to/igorzanelladev";
export const SPOTIFY_URL =
  "https://open.spotify.com/user/11126271502?si=bbe625bd9431448a";
export const TWITTER_ID = "@IgorZanellaDev";
export const MEDIUM_URL = "https://medium.com/@igorzanella.dev";
