import { Technology, TechnologyId, TechnologyType } from "@/types/technology";

export const TECHNOLOGIES: Technology[] = [
  {
    id: TechnologyId.Typescript,
    name: "Typescript",
    icon: "ts",
    link: "https://www.typescriptlang.org/",
    type: TechnologyType.Frontend,
  },
  { id: TechnologyId.React, name: "React", icon: "react", link: "https://react.dev/", type: TechnologyType.Frontend },
  {
    id: TechnologyId.ReactNative,
    name: "React Native",
    icon: "react",
    link: "https://reactnative.dev/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Nextjs,
    name: "NextJS",
    icon: "nextjs",
    link: "https://nextjs.org/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Gatsby,
    name: "Gatsby",
    icon: "gatsby",
    link: "https://www.gatsbyjs.com/",
    type: TechnologyType.Frontend,
  },
  { id: TechnologyId.Vite, name: "Vite", icon: "vite", link: "https://vite.dev/", type: TechnologyType.Frontend },
  {
    id: TechnologyId.Tanstack,
    name: "Tanstack Query",
    icon: "tanstack",
    link: "https://tanstack.com/query/latest",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Graphql,
    name: "GraphQL",
    icon: "graphql",
    link: "https://graphql.org/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Tailwind,
    name: "TailwindCSS",
    icon: "tailwind",
    link: "https://tailwindcss.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.StyledComponents,
    name: "Styled Components",
    icon: "styled-components",
    link: "https://styled-components.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Shadcn,
    name: "shadcn/ui",
    icon: "shadcn",
    themeChange: true,
    link: "https://ui.shadcn.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Bootstrap,
    name: "Bootstrap",
    icon: "bootstrap",
    link: "https://getbootstrap.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.SocketIo,
    name: "Socket.io",
    icon: "socket-io",
    themeChange: true,
    link: "https://socket.io/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Recoil,
    name: "Recoil",
    icon: "recoil",
    link: "https://recoiljs.org/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Jotai,
    name: "Jotai",
    icon: "jotai",
    link: "https://jotai.org/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.Redux,
    name: "Redux",
    icon: "redux",
    link: "https://redux.js.org/",
    type: TechnologyType.Frontend,
  },
  {
    id: TechnologyId.I18next,
    name: "i18next",
    icon: "i18next",
    link: "https://www.i18next.com/",
    type: TechnologyType.Frontend,
  },
  { id: TechnologyId.Npm, name: "npm", icon: "npm", link: "https://www.npmjs.com/", type: TechnologyType.Frontend },
  { id: TechnologyId.Yarn, name: "yarn", icon: "yarn", link: "https://yarnpkg.com/", type: TechnologyType.Frontend },

  {
    id: TechnologyId.Nodejs,
    name: "NodeJS",
    icon: "nodejs",
    link: "https://nodejs.org/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Nestjs,
    name: "NestJS",
    icon: "nestjs",
    link: "https://nestjs.com/",
    type: TechnologyType.Backend,
  },
  { id: TechnologyId.Php, name: "PHP", icon: "php", link: "https://www.php.net/", type: TechnologyType.Backend },
  {
    id: TechnologyId.Symfony,
    name: "Symfony",
    icon: "symfony",
    themeChange: true,
    link: "https://symfony.com/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Postgresql,
    name: "PostgreSQL",
    icon: "postgresql",
    link: "https://www.postgresql.org/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Mysql,
    name: "MySQL",
    icon: "mysql",
    link: "https://www.mysql.com/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Mongodb,
    name: "MongoDB",
    icon: "mongodb",
    link: "https://www.mongodb.com/",
    type: TechnologyType.Backend,
  },
  { id: TechnologyId.Redis, name: "Redis", icon: "redis", link: "https://redis.io/", type: TechnologyType.Backend },
  {
    id: TechnologyId.Contentful,
    name: "Contentful",
    icon: "contentful",
    link: "https://www.contentful.com/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Wordpress,
    name: "Wordpress",
    icon: "wordpress",
    link: "https://wordpress.org/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Onesignal,
    name: "OneSignal",
    icon: "onesignal",
    link: "https://onesignal.com/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Stripe,
    name: "Stripe",
    icon: "stripe",
    link: "https://stripe.com/",
    type: TechnologyType.Backend,
  },
  {
    id: TechnologyId.Python,
    name: "Python",
    icon: "python",
    link: "https://www.python.org/",
    type: TechnologyType.Backend,
  },

  {
    id: TechnologyId.Docker,
    name: "Docker",
    icon: "docker",
    link: "https://www.docker.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Linux,
    name: "Linux",
    icon: "linux",
    link: "https://www.kernel.org/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Openai,
    name: "OpenAI",
    icon: "openai",
    themeChange: true,
    link: "https://openai.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Aws,
    name: "AWS",
    icon: "aws",
    link: "https://aws.amazon.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Nginx,
    name: "Nginx",
    icon: "nginx",
    link: "https://nginx.org/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Azure,
    name: "Azure",
    icon: "azure",
    link: "https://azure.microsoft.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Terraform,
    name: "Terraform",
    icon: "terraform",
    link: "https://www.terraform.io/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Circleci,
    name: "CircleCI",
    icon: "circleci",
    themeChange: true,
    link: "https://circleci.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Vercel,
    name: "Vercel",
    icon: "vercel",
    themeChange: true,
    link: "https://vercel.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Supabase,
    name: "Supabase",
    icon: "supabase",
    link: "https://supabase.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.GithubActions,
    name: "GitHub Actions",
    icon: "github",
    themeChange: true,
    link: "https://github.com/features/actions",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Pinecone,
    name: "Pinecone",
    icon: "pinecone",
    themeChange: true,
    link: "https://www.pinecone.io/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Cloudflare,
    name: "Cloudflare",
    icon: "cloudflare",
    link: "https://www.cloudflare.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Grafana,
    name: "Grafana",
    icon: "grafana",
    link: "https://grafana.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Prometheus,
    name: "Prometheus",
    icon: "prometheus",
    link: "https://prometheus.io/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Elastic,
    name: "Elasticsearch",
    icon: "elastic",
    link: "https://www.elastic.co/elasticsearch/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Qualys,
    name: "Qualys",
    icon: "qualys",
    link: "https://www.qualys.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Nimbus,
    name: "Nimbus",
    icon: "nimbus",
    themeChange: true,
    link: "https://nimbus.team/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: TechnologyId.Besu,
    name: "Besu",
    icon: "besu",
    themeChange: true,
    link: "https://besu.hyperledger.org/",
    type: TechnologyType.Infrastructure,
  },
];

export const TECHNOLOGIES_BY_TYPE = TECHNOLOGIES.reduce(
  (acc, tech) => {
    acc[tech.type] = [...(acc[tech.type] || []), tech];
    return acc;
  },
  {} as Record<TechnologyType, Technology[]>,
);

export const TECHNOLOGIES_BY_ID = TECHNOLOGIES.reduce(
  (acc, tech) => {
    acc[tech.id as TechnologyId] = tech;
    return acc;
  },
  {} as Record<TechnologyId, Technology>,
);
