import { Technology, TechnologyType } from "@/types/technology";

export const TECHNOLOGIES: Technology[] = [
  { id: "ts", name: "Typescript", icon: "ts", link: "https://www.typescriptlang.org/", type: TechnologyType.Frontend },
  { id: "react", name: "React", icon: "react", link: "https://react.dev/", type: TechnologyType.Frontend },
  {
    id: "react-native",
    name: "React Native",
    icon: "react",
    link: "https://reactnative.dev/",
    type: TechnologyType.Frontend,
  },
  { id: "nextjs", name: "NextJS", icon: "nextjs", link: "https://nextjs.org/", type: TechnologyType.Frontend },
  { id: "vite", name: "Vite", icon: "vite", link: "https://vite.dev/", type: TechnologyType.Frontend },
  {
    id: "tanstack",
    name: "Tanstack Query",
    icon: "tanstack",
    link: "https://tanstack.com/query/latest",
    type: TechnologyType.Frontend,
  },
  {
    id: "tailwind",
    name: "TailwindCSS",
    icon: "tailwind",
    link: "https://tailwindcss.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: "styled-components",
    name: "Styled Components",
    icon: "styled-components",
    link: "https://styled-components.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    icon: "shadcn",
    themeChange: true,
    link: "https://ui.shadcn.com/",
    type: TechnologyType.Frontend,
  },
  {
    id: "socket-io",
    name: "Socket.io",
    icon: "socket-io",
    themeChange: true,
    link: "https://socket.io/",
    type: TechnologyType.Frontend,
  },
  {
    id: "recoil",
    name: "Recoil",
    icon: "recoil",
    link: "https://recoiljs.org/",
    type: TechnologyType.Frontend,
  },
  {
    id: "i18next",
    name: "i18next",
    icon: "i18next",
    link: "https://www.i18next.com/",
    type: TechnologyType.Frontend,
  },
  { id: "npm", name: "npm", icon: "npm", link: "https://www.npmjs.com/", type: TechnologyType.Frontend },
  { id: "yarn", name: "yarn", icon: "yarn", link: "https://yarnpkg.com/", type: TechnologyType.Frontend },

  { id: "nodejs", name: "NodeJS", icon: "nodejs", link: "https://nodejs.org/", type: TechnologyType.Backend },
  { id: "nestjs", name: "NestJS", icon: "nestjs", link: "https://nestjs.com/", type: TechnologyType.Backend },
  { id: "php", name: "PHP", icon: "php", link: "https://www.php.net/", type: TechnologyType.Backend },
  {
    id: "symfony",
    name: "Symfony",
    icon: "symfony",
    themeChange: true,
    link: "https://symfony.com/",
    type: TechnologyType.Backend,
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "postgresql",
    link: "https://www.postgresql.org/",
    type: TechnologyType.Backend,
  },
  { id: "mysql", name: "MySQL", icon: "mysql", link: "https://www.mysql.com/", type: TechnologyType.Backend },
  { id: "mongodb", name: "MongoDB", icon: "mongodb", link: "https://www.mongodb.com/", type: TechnologyType.Backend },
  { id: "redis", name: "Redis", icon: "redis", link: "https://redis.io/", type: TechnologyType.Backend },
  {
    id: "contentful",
    name: "Contentful",
    icon: "contentful",
    link: "https://www.contentful.com/",
    type: TechnologyType.Backend,
  },
  {
    id: "wordpress",
    name: "Wordpress",
    icon: "wordpress",
    link: "https://wordpress.org/",
    type: TechnologyType.Backend,
  },
  {
    id: "onesignal",
    name: "OneSignal",
    icon: "onesignal",
    link: "https://onesignal.com/",
    type: TechnologyType.Backend,
  },
  { id: "stripe", name: "Stripe", icon: "stripe", link: "https://stripe.com/", type: TechnologyType.Backend },
  { id: "python", name: "Python", icon: "python", link: "https://www.python.org/", type: TechnologyType.Backend },

  {
    id: "docker",
    name: "Docker",
    icon: "docker",
    link: "https://www.docker.com/",
    type: TechnologyType.Infrastructure,
  },
  { id: "linux", name: "Linux", icon: "linux", link: "https://www.kernel.org/", type: TechnologyType.Infrastructure },
  {
    id: "openai",
    name: "OpenAI",
    icon: "openai",
    themeChange: true,
    link: "https://openai.com/",
    type: TechnologyType.Infrastructure,
  },
  { id: "aws", name: "AWS", icon: "aws", link: "https://aws.amazon.com/", type: TechnologyType.Infrastructure },
  { id: "nginx", name: "Nginx", icon: "nginx", link: "https://nginx.org/", type: TechnologyType.Infrastructure },
  {
    id: "azure",
    name: "Azure",
    icon: "azure",
    link: "https://azure.microsoft.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "terraform",
    name: "Terraform",
    icon: "terraform",
    link: "https://www.terraform.io/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "circleci",
    name: "CircleCI",
    icon: "circleci",
    themeChange: true,
    link: "https://circleci.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: "vercel",
    themeChange: true,
    link: "https://vercel.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "supabase",
    name: "Supabase",
    icon: "supabase",
    link: "https://supabase.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "github",
    name: "GitHub Actions",
    icon: "github",
    themeChange: true,
    link: "https://github.com/features/actions",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "pinecone",
    name: "Pinecone",
    icon: "pinecone",
    themeChange: true,
    link: "https://www.pinecone.io/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    icon: "cloudflare",
    link: "https://www.cloudflare.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "grafana",
    name: "Grafana",
    icon: "grafana",
    link: "https://grafana.com/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "prometheus",
    name: "Prometheus",
    icon: "prometheus",
    link: "https://prometheus.io/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "elastic",
    name: "Elasticsearch",
    icon: "elastic",
    link: "https://www.elastic.co/elasticsearch/",
    type: TechnologyType.Infrastructure,
  },
  {
    id: "qualys",
    name: "Qualys",
    icon: "qualys",
    link: "https://www.qualys.com/",
    type: TechnologyType.Infrastructure,
  },
];

export const TECHNOLOGIES_BY_TYPE = TECHNOLOGIES.reduce(
  (acc, tech) => {
    acc[tech.type] = [...(acc[tech.type] || []), tech];
    return acc;
  },
  {} as Record<TechnologyType, Technology[]>,
);

export const TECHNOLOGIES_BY_ID = TECHNOLOGIES.reduce(
  (acc, tech) => {
    acc[tech.id] = tech;
    return acc;
  },
  {} as Record<string, Technology>,
);
