import IubendaScripts from "@/components/iubenda-scripts";
import Menu from "@/components/menu";
import Footer from "@/components/menu/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { GTM_ID } from "@/constants/seo";
import { GoogleTagManager } from "@next/third-parties/google";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html suppressHydrationWarning lang={"en"} className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
      <GoogleTagManager gtmId={GTM_ID} />
      <body className={"mx-auto flex flex-col gap-2 md:max-w-screen-lg md:flex-row"}>
        <ThemeProvider disableTransitionOnChange enableSystem attribute={"class"} defaultTheme={"system"}>
          <IubendaScripts />
          <Menu />
          <div className={"flex flex-1 flex-col overflow-x-hidden"}>
            <main className={"flex flex-col p-4 md:mt-4 md:p-8 md:pb-4"}>{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
