import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html suppressHydrationWarning lang={"en"} className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
      <body className={"mx-auto mt-4 flex max-w-screen-lg gap-2"}>
        <ThemeProvider disableTransitionOnChange enableSystem attribute={"class"} defaultTheme={"system"}>
          <Sidebar />
          <main className={"flex flex-1 flex-col overflow-x-hidden p-8"}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
