import IubendaScripts from "@/components/iubenda-scripts";
import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { GTM_ID } from "@/constants/seo";
import { GoogleTagManager } from "@next/third-parties/google";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html suppressHydrationWarning lang={"en"} className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
      <GoogleTagManager gtmId={GTM_ID} />
      <body className={"mx-auto flex max-w-screen-lg gap-2"}>
        <ThemeProvider disableTransitionOnChange enableSystem attribute={"class"} defaultTheme={"system"}>
          <IubendaScripts />
          <Sidebar />
          <main className={"mt-4 flex flex-1 flex-col overflow-x-hidden p-8"}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
